version: "3.8"

services:
  # api:
  # build:
  #   context: .
  #   dockerfile: Dockerfile
  # ports:
  #   - "3000:3000"
  # environment:
  #   - NODE_ENV=production
  #   - PORT=3000
  #   - DATABASE_URL=postgresql://user:password@postgres:5432/wishlist?schema=public
  #   - REDIS_URL=redis://redis:6379
  #   - JWT_SECRET=${JWT_SECRET}
  # depends_on:
  #   postgres:
  #     condition: service_healthy
  #   redis:
  #     condition: service_healthy
  # networks:
  #   - wishlist-network
  # volumes:
  #   - .:/app
  # command: npm start

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wishlist
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d wishlist"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wishlist-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wishlist-network

volumes:
  postgres-data:

networks:
  wishlist-network:
    driver: bridge
